export const NEW_STAFFS = 'NEW_STAFFS';
export const STAFF_LOADING = 'STAFF_LOADING';
export const STAFF_ERROR = 'STAFF_ERROR';
export const STAFF_UPDATE = 'STAFF_UPDATE';
export const STAFF_DELETE = 'STAFF_DELETE';

export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING' ;
export const DEPARTMENT_ADD = 'DEPARTMENT_ADD';
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR';

export const SALARY_LOADING = 'SALARY_LOADING' ;
export const SALARY_ADD = 'SALARY_ADD';
export const SALARY_ERROR = 'SALARY_ERROR';

export const DEPARTMENTSTAFFS_LOADING = 'DEPARTMENTSTAFFS_LOADING' ;
export const DEPARTMENTSTAFFS_ADD = 'DEPARTMENTSTAFFS_ADD';
export const DEPARTMENTSTAFFS_ERROR = 'DEPARTMENTSTAFFS_ERROR';

export const PAYROLL_LOADING = 'PAYROLL_LOADING' ;
export const PAYROLL_ADD = 'PAYROLL_ADD';
export const PAYROLL_ERROR = 'PAYROLL_ERROR';
